a = int(input("enter the first integer: "))
b = int(input("enter the second integer: "))
print(f"a+b: {a+b}")
print(f"a-b: {a-b}")
print(f"a*b: {a*b}")
print(f"a/b: {a/b}")
print(f"a//b: {a//b}")
print(f"a**b: {a**b}")
print(f"a%b: {a%b}")